baseURL = 'https://unsearch.org'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'lowkey'
title = 'UnSearch'
enableRobotsTXT = true

# List Config
summaryLength= 15
paginate = 5

[markup.highlight]
      codeFences = false
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research"
    weight = 10
